E=export PATH=$(CURDIR)/node-v8.9.4-linux-x64:$$PATH;

prepare:
	wget https://nodejs.org/dist/v8.9.4/node-v8.9.4-linux-x64.tar.xz
	tar xvf node-v8.9.4-linux-x64.tar.xz
	$(E)npm i --save headless-chrome-crawler
	$(E)npm i --save mongoose

