// Generated by CIRCT firtool-1.62.1
module Foo(
  input        clock,
               reset,
               a,
               b,
               c,
               d,
               e,
               f,
  input  [7:0] foo,
               bar,
  output [7:0] out
);

  reg [7:0] myReg;
  always @(posedge clock) begin
    if (reset)
      myReg <= 8'h0;
    else if (d & e & f)
      myReg <= bar;
    else if (a & b & c)
      myReg <= foo;
  end // always @(posedge)
  assign out = myReg;
endmodule


