all:
	sudo apt-get install python-pyqtgraph

e:
	python -m pyqtgraph.examples

q:
	sudo apt-get install python3-pyqt5.qtchart python3-pyqt5.qtwebkit



prep:
	git clone https://github.com/pyqtgraph/pyqtgraph.git
	cd pyqtgraph; python setup.py install --user
	cd pyqtgraph; python3 setup.py install --user
