/* Generated by Yosys 0.7 (git sha1 61f6811) */

(* top =  1  *)
(* generator = "nMigen" *)
module top(v_m, sel, a, b, rec_l, o, co, v_l);
  wire \$1 ;
  wire \$11 ;
  wire [15:0] \$13 ;
  wire [15:0] \$15 ;
  wire [15:0] \$17 ;
  wire [16:0] \$19 ;
  wire \$3 ;
  wire \$5 ;
  wire \$7 ;
  wire \$9 ;
  (* src = "rec.py:22" *)
  reg \$next\co ;
  (* src = "rec.py:21" *)
  reg [15:0] \$next\o ;
  (* src = "/home/eiselekd/git/lang/python/migen/nmigen/nmigen/hdl/rec.py:87" *)
  reg \$next\rec_l ;
  (* src = "/home/eiselekd/git/lang/python/migen/nmigen/nmigen/hdl/rec.py:87" *)
  reg [1:0] \$next\rec_m ;
  (* src = "rec.py:19" *)
  input [15:0] a;
  (* src = "rec.py:20" *)
  input [15:0] b;
  (* src = "rec.py:22" *)
  output co;
  (* src = "rec.py:21" *)
  output [15:0] o;
  (* src = "/home/eiselekd/git/lang/python/migen/nmigen/nmigen/hdl/rec.py:87" *)
  output rec_l;
  (* src = "/home/eiselekd/git/lang/python/migen/nmigen/nmigen/hdl/rec.py:87" *)
  wire [1:0] rec_m;
  (* src = "rec.py:18" *)
  input [1:0] sel;
  (* src = "/home/eiselekd/git/lang/python/migen/nmigen/nmigen/hdl/rec.py:87" *)
  input v_l;
  (* src = "/home/eiselekd/git/lang/python/migen/nmigen/nmigen/hdl/rec.py:87" *)
  input [1:0] v_m;
  assign \$9  = sel == (* src = "rec.py:35" *) 1'b1;
  assign \$11  = sel == (* src = "rec.py:37" *) 2'b10;
  assign \$13  = a | (* src = "rec.py:33" *) b;
  assign \$15  = a & (* src = "rec.py:36" *) b;
  assign \$17  = a ^ (* src = "rec.py:38" *) b;
  assign \$1  = sel == (* src = "rec.py:32" *) 1'b0;
  assign \$19  = a - (* src = "rec.py:40" *) b;
  assign \$3  = sel == (* src = "rec.py:35" *) 1'b1;
  assign \$5  = sel == (* src = "rec.py:37" *) 2'b10;
  assign \$7  = sel == (* src = "rec.py:32" *) 1'b0;
  always @* begin
    \$next\rec_l  = 1'b0;
    \$next\rec_m  = 2'b00;
    { \$next\rec_m , \$next\rec_l  } = { v_m, v_l };
    casez ({ \$5 , \$3 , \$1  })
      3'bzz1:
          \$next\rec_l  = a[0];
      3'bz1z:
          /* empty */;
      3'b1zz:
          /* empty */;
      3'bzzz:
          /* empty */;
    endcase
  end
  always @* begin
    \$next\o  = 16'b0000000000000000;
    \$next\co  = 1'b0;
    casez ({ \$11 , \$9 , \$7  })
      3'bzz1:
          \$next\o  = \$13 ;
      3'bz1z:
          \$next\o  = \$15 ;
      3'b1zz:
          \$next\o  = \$17 ;
      3'bzzz:
          { \$next\co , \$next\o  } = \$19 ;
    endcase
  end
  assign o = \$next\o ;
  assign co = \$next\co ;
  assign rec_l = \$next\rec_l ;
  assign rec_m = \$next\rec_m ;
endmodule

